export const PRESET_TOPICS = [
  'Should India adopt a Universal Basic Income?',
  'Is remote work the future of corporate culture?',
  'Should startups prioritize growth over profitability?',
  'Is ESG investing a fad or the future of business?',
  'Should large corporations be broken up to prevent monopolies?',
  'Is the gig economy exploiting workers?',
  'Should cryptocurrency be regulated or banned in India?',
  'Is India ready to become a global manufacturing hub?',
  'Has social media done more harm than good to society?',
  'Should voting be made mandatory in India?',
  'Is capitalism the best economic system for developing nations?',
  'Should higher education be free for all?',
  'Is urbanization good or bad for India\'s future?',
  'Should India adopt a Uniform Civil Code?',
  'Will AI replace more jobs than it creates?',
  'Should social media platforms be regulated like public utilities?',
  'Is data privacy a luxury only the rich can afford?',
  'Should autonomous vehicles be allowed on Indian roads?',
  'Is India ready to become a developed nation by 2047?',
  'Is cricket doing more harm than good to Indian sports culture?',
  'Should India invest more in renewable energy or nuclear power?',
  'Is the startup ecosystem in India sustainable long-term?',
];
